### ISSUE TITLE
Add safe.trade to exchanges

### ISSUE THREAD

**Issue by egyptianbman** [bitcoinz-sites/btcz.rocks#63]
We need to add safe.trade to the list of exchanges on the site.

**Comment by gilardh** [comment]
The logo 'SafeCoin' is a coin not a exchange but the link is correct because he is returning to https://safe.trade/trading/btczbtc
I propose to put the correct logo of the exchange Safe.coin

![20181211 safetrade](https://user-images.githubusercontent.com/39105646/49767988-f21f2e80-fcda-11e8-9881-3128d32832d9.jpg)

**Comment by gilardh** [comment]
See https://github.com/bitcoinz-sites/btcz.rocks/pull/67

**Comment by egyptianbman** [comment]
Thanks, @gilardh !
